### ISSUE TITLE
create Url abstract

### ISSUE THREAD

**Issue by fponticelli** [fponticelli/thx.core#11]
or Uri

**Comment by fponticelli** [comment]
good and simple reference https://nodejs.org/api/url.html

**Comment by jasononeil** [comment]
These would be great.  I'd definitely use them in ufront.

How about email while you're at it?

**Comment by fponticelli** [comment]
@jasononeil `thx.core.Url` and `thx.core.QueryString` made into master. Please let me know waht you think before I make a release.

**Comment by jasononeil** [comment]
Both look good.  I agree with what you said in #37, having a base `MultiValueMap<T>` type would be a nice bonus.

One minor nitpick: you have different casing conventions for `UUID` and `Url`.  Is this intentional?  For what it's worth, the standard library seems to have standardised on `Url` rather than `URL`.

**Comment by fponticelli** [comment]
I don't know why Uuid feels wrong but Url doesn't :) ... I will try to
unify acronyms all around.

Il giorno mar 24 mar 2015 alle ore 03:23 jasononeil <
notifications@github.com> ha scritto:

**Comment by fponticelli** [comment]
UUID is now Uuid.
