### ISSUE TITLE
Why is Set backed by an Array instead of a Map/Object/Hash?

### ISSUE THREAD

**Issue by dionjwa** [fponticelli/thx.core#77]
I intuitively think that 'exists' operations will be fast on a Set, since in other languages they're hash maps with no values. Otherwise they don't scale well for large numbers of items, whereas hash based sets use a fast lookup.

**Comment by fponticelli** [comment]
Your intuition is most likely correct. The reason is that Set (like Array) preserve the order of insertion. A Map will not guarantee the same behavior (it will in some platforms like JS). That said I am open to reconsider and have maybe 2 separate types. That might actually be a good idea since we already have MapList that is an ordered Map. So we can have SetList with the same behavior. What do you think? PR are obviously much welcome.

**Comment by dionjwa** [comment]
Yeah before I think about a PR I need to know what your intention is. Sets are usually assumed to be unordered, like maps, since the mathematical definition is unordered, and you get fast lookups in exchange for no ordering. So if you were going to have an ordered set, you would build in on top of a set and call it an OrderedSet, so that as a developer you know that you're getting extra functionality as a price (e.g. the extra array to record insertion order). So if this sounds reasonable to you, I'll think about a PR.

**Comment by fponticelli** [comment]
Agreed, sounds totally reasonable

Il giorno dom 20 set 2015 alle ore 01:21 Dion Whitehead Amago <
notifications@github.com> ha scritto:

**Comment by fponticelli** [comment]
It is not committed, creating `Set` instances it is now a little more complicated but should work. Please let me know if it works for you.
